import type { Metadata } from "next";
import { GeistSans, GeistMono } from "geist/font";
import "./globals.css";
import Header from "@/components/Header";
import { SmoothScrollProviders } from "@/providers/SmoothScrollProviders";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <Header />
        <SmoothScrollProviders options={{ smooth: true }}>
          {children}
        </SmoothScrollProviders>
      </body>
    </html>
  );
}
